### ISSUE TITLE
Error: listen EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by spillsthrills** [softwareCobbler/cfc#6]
Any workarounds for this error?

Windows 10 Pro 10.0.19043
Vs Code 1.64.1
Node.js 14.16.0

Error: listen EADDRINUSE: address already in use \\.\pipe\cfls-token-edfee943cd9797495aeb64a0b945fdcb
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
    at Object.requestCancellation (c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:47:16)
    at pushTask (c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:328:35)
    at Object.emitDiagnostics (c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:313:9)
    at runDiagonstics (c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:10003:25)
    at c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:10019:5
    at CallbackList.invoke (c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:1783:39)
    at Emitter.fire (c:\Users\me\.vscode\extensions\davidrogers.cflsp-1.0.33\out\server.js:1845:36)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '\\\\.\\pipe\\cfls-token-edfee943cd9797495aeb64a0b945fdcb',
  port: -1

**Comment by softwareCobbler** [comment]
I think this is a race between `net.listen(pipeName)` and `if (net.listening()) { ... }`
Curious if you are in a multiroot workspace, where 2 or more workspace roots have CF files in them?

**Comment by spillsthrills** [comment]
This workspace is not multiroot. I am gonna go the route that this could be an extension conflict?

**Comment by softwareCobbler** [comment]
I don't know how to build a test for it, but can reproduce it manually by loading a project on a Windows machine and just typing as fast as possible into a CF file (just mashing keys works)

The core of the issue appears to be :
```
// cancellation token setup
let token = net.createServer();

// request cancellation
token.listen("\\.pipe\cfls-token-...");

// reset cancellation token
token.close();

// later, request another cancellation
if (!token.listening) { // <-- windows says "token.listening=false", but the socket is not actually closed
    token.listen("\\.pipe\cfls-token-..."); // oops, EADDRINUSE
}
```

Should be fixed in most recent commit, node allows for callbacks in `close` to get better control over the socket's state and we can get the right answer for `token.listening`

This will be included in the next release, slated to be 1.4. No definite deadline for that, but your welcome to build from `main` and use a local copy.

**Comment by softwareCobbler** [comment]
1.0.4 is out (said 1.4 above but that was a typo). The bug should be fixed, but this can be the permanent home to any new or recurring EADDRINUSE issues.

**Comment by spillsthrills** [comment]
Working great and thank you for such a quick turn around!
